### ISSUE TITLE
Problema con commits

### ISSUE THREAD

**Issue by JohnJasso** [UG-InternetApps/Tareas#1]
Buenas noches, profe.

Sólo es con un asunto sobre la tarea, al hacer los ejercicios inicié git dentro de la carpeta javascripting, que está dentro de la carpeta NodeSchool. En la carpeta NodeSchool también inicié git, pero todos los commits los hice dentro de javascripting. En el repo NodeSchool-Solutions entonces sólo tendría un commit que agrega la carpeta javascripting con todos los archivos de los 19 ejercicios. ¿Está bien de esta manera? ¿O añado el origin del repositorio dentro de la carpeta javascripting en lugar de dentro de NodeSchool?

**Comment by JuanCrg90** [comment]
Solo debes iniciar el git en la raiz de tu proyecto, osea el directorio de Nodeschool. idealmente yo espero ver 19 commits. 
- Puedes borrar los dos git.
- iniciarlo solo  en el directorio raiz
- y hacer commit archivo por archivo
- `git add <filename>`
- `git commit`

**Comment by cbotello** [comment]
¿Los commits los hacemos de manera local y al final solo hacemos 1 solo push?

**Comment by JuanCrg90** [comment]
el push es a tu consideración, el push solo se encarga de enviarlo a internet, puedes hacer uno con los 19, o un push por cada commit
