### ISSUE TITLE
Página para Imagenes

### ISSUE THREAD

**Issue by JavierSLX** [UG-InternetApps/Tareas#2]
Buen día Juan Carlos, molesto con duda. ¿Qué servicio puedo usar (o que me recomiendes) para subir imágenes para colocarlas en Markdown? Ya probé con 3 servicios gratuitos y me baja bastante la calidad de éstas. Saludos y gracias.

**Comment by JuanCrg90** [comment]
yo uso http://cloudinary.com/ tambien puedes agregar las imagenes a tu repo hacer push y luego hacer uso de ellas en el markdown
