### ISSUE TITLE
Aviso Clase

### ISSUE THREAD

**Issue by JuanCrg90** [UG-InternetApps/Tareas#4]
Jóvenes, amanecí mal de la garganta, no me encuentro en condiciones de impartir clase. una disculpa, nos vemos el martes para seguir con el curso.

**Comment by IsabelVillafuerte** [comment]
No se preocupe profesor, espero que se recupere pronto y nos vemos el martes!

**Comment by ErickMtz** [comment]
ok profe que se mejore
